#!/usr/bin/env Rscript

library(tidyverse)

# ---------- HARDCODED FILE PATHS ----------
gene_color_file <- "gene_colors.csv"

log2fc_d2_d0_file <- "D2_D0.csv"
log2fc_d7_d2_file <- "D7_D2.csv"
log2fc_d7_d0_file <- "D7_D0.csv"

pathways_d2_d0_file <- "pathways_D2_D0.csv"
pathways_d7_d2_file <- "pathways_D7_D2.csv"
pathways_d7_d0_file <- "pathways_D7_D0.csv"

outfile <- "gene_colors_with_log2fc_and_pathways.csv"

# ---------- HARDCODED PATHWAYS TO FOCUS ON ----------
focus_pathways <- c(
  "Pathway_A",
  "Pathway_B",
  "Pathway_C"
)

# ---------- HELPERS ----------
read_log2fc <- function(file, new_colname) {
  read_csv(file, show_col_types = FALSE) %>%
    select(1, 2) %>%
    transmute(
      Gene = as.character(.[[1]]),
      !!new_colname := as.numeric(.[[2]])
    ) %>%
    distinct(Gene, .keep_all = TRUE)
}

read_reactive_pathways <- function(file, new_colname) {
  read_csv(file, show_col_types = FALSE) %>%
    select(2, 13) %>%
    transmute(
      pathway = as.character(.[[1]]),
      genes = as.character(.[[2]])
    ) %>%
    filter(pathway %in% focus_pathways) %>%
    separate_rows(genes, sep = ",") %>%
    mutate(Gene = str_trim(genes)) %>%
    filter(!is.na(Gene), Gene != "") %>%
    group_by(Gene) %>%
    summarise(
      !!new_colname := paste(unique(pathway), collapse = ", "),
      .groups = "drop"
    )
}

# ---------- LOAD BASE ----------
gene_colors <- read_csv(gene_color_file, show_col_types = FALSE) %>%
  mutate(Gene = as.character(Gene))

# ---------- LOAD LOG2FC FILES ----------
d2_d0 <- read_log2fc(log2fc_d2_d0_file, "log2fc_D2_v_D0")
d7_d2 <- read_log2fc(log2fc_d7_d2_file, "log2fc_D7_v_D2")
d7_d0 <- read_log2fc(log2fc_d7_d0_file, "log2fc_D7_v_D0")

# ---------- LOAD PATHWAY FILES ----------
p_d2_d0 <- read_reactive_pathways(pathways_d2_d0_file, "pathways_D2_v_D0")
p_d7_d2 <- read_reactive_pathways(pathways_d7_d2_file, "pathways_D7_v_D2")
p_d7_d0 <- read_reactive_pathways(pathways_d7_d0_file, "pathways_D7_v_D0")

# ---------- JOIN EVERYTHING ----------
out <- gene_colors %>%
  left_join(d2_d0, by = "Gene") %>%
  left_join(d7_d2, by = "Gene") %>%
  left_join(d7_d0, by = "Gene") %>%
  left_join(p_d2_d0, by = "Gene") %>%
  left_join(p_d7_d2, by = "Gene") %>%
  left_join(p_d7_d0, by = "Gene")

# ---------- SAVE ----------
write_csv(out, outfile, na = "")
